server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/db_api_v1_evento
    username: {{username_db}}
    password: {{password_db}}
    driver-class-name: com.mysql.cj.jdbc.Driver
